server:
  tomcat:
    threads:
      max: ${TOMCAT_THREADS_MAX:200}
      min-spare: ${TOMCAT_THREADS_MIN_SPARE:10}

    max-connections: ${TOMCAT_MAX_CONNECTIONS:8192}
    accept-count: ${TOMCAT_ACCEPT_COUNT:100}

    connection-timeout: ${TOMCAT_CONNECTION_TIMEOUT:60s}
    keep-alive-timeout: ${TOMCAT_KEEP_ALIVE_TIMEOUT:60s}

spring:
  application:
    name: bottari
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}   # ms
      max-lifetime: ${HIKARI_MAX_LIFETIME:1800000}             # ms
      minimum-idle: ${HIKARI_MIN_IDLE:10}

  sql:
    init:
      mode: always
      data-locations: classpath:init.sql
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: false
  servlet:
    multipart:
      enabled: true # 멀티파트 업로드 지원여부 (default: true)
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)
firebase:
  service:
    key-path: ${FIREBASE_SERVICE_ACCOUNT_JSON}

app:
  s3:
    bucket: bottari-local
