spring:
  application:
    name: bottari
  jpa:
    show-sql: true   # SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    open-in-view: true
  sql:
    init:
      mode: always


firebase:
  service:
     key-path: ${FIREBASE_SERVICE_ACCOUNT_JSON}
