CHANGE REPLICATION SOURCE TO
  SOURCE_HOST='bottari-master',
  SOURCE_USER='repl',
  SOURCE_PASSWORD='repl1234',
  SOURCE_LOG_FILE='mysql-bin.000001',
  SOURCE_LOG_POS=0,
  SOURCE_DELAY=1,
  GET_SOURCE_PUBLIC_KEY=1;

START REPLICA;
