# ????? ??? ???? ?? ?? ??? ?? (???? CPU?? ?? ???)
org.gradle.parallel=true
# ?? ??(??? ??? ?)? ???? ??? ??? ??? ? ???? ??? ??
org.gradle.caching=true
# ??? configuration ?? ??? ???? ?? ????? ?? ??? ?? ? ?? ?? ?? ??
org.gradle.configuration-cache=true
# configuration ?? ?? ??? ??? ???? ?? ?? ??? ?? ??? ?
org.gradle.configuration-cache.parallel=true
